// 시작 · 모듈 연결. 규칙(core)과 화면(render/ui/town)은 여기서만 이어진다.
import * as C from './core/clock.js';
import { playerMove } from './core/combat.js';
import { computeFOV } from './core/fov.js';
import { calcStats, equip, gearName, makeGear, makeUnrand, pickGear, refreshStats, rollGear, unequip } from './core/gear.js';
import { openHidden } from './core/hidden.js';
import { useItem } from './core/items.js';
import { genFloor } from './core/mapgen.js';
import { META, loadMeta, newHero, processReturn, resetMeta } from './core/meta.js';
import { newRun } from './core/run.js';
import * as Settle from './core/settlement.js';
import { G, Game, setListener } from './core/state.js';
import { addStone, inCombat, reduceColor, stoneCd, useStone } from './core/stones.js';
import { takeTorch, volunteers } from './core/succession.js';
import { acceptVisitor, glowParts, hearthGlow, requestState, rollVisitors } from './core/visitors.js';
import { DROPS } from './data/enemies.js';
import { STONE } from './data/stones.js';
import { RECIPES } from './data/town.js';
import { Loop, act, descend, enterDungeon, returnToTown } from './flow.js';
import { ports } from './render/ports.js';
import { Sfx } from './render/sfx.js';
import { View } from './render/view.js';
import { Town } from './town/town.js';
import { $, UI } from './ui/ui.js';
import './render/fx.js';
import './render/gear-view.js';
import './render/hidden-view.js';
import './ui/inventory.js';
import './ui/input.js';
import './ui/joystick.js';
import './ui/hud.js';
import './ui/status.js';
import './ui/panels.js';
import './ui/screens.js';
import './town/town-ui.js';
import './town/hearth.js';
import './town/visitor-ui.js';
import './town/build-ui.js';

setListener((type, data) => View.on(type, data));
Object.assign(ports, { UI, Town, Loop });

/* ================= 시작 ================= */
View.init();
UI.init();
UI.joyInit();
for (const b of document.querySelectorAll('#tbtns button')) b.onclick = () => { if (Town.busy) return; const o = b.dataset.o; if (o === 'craft') Town.craft(); else if (o === 'build') Town.enterBuild(); else if (o === 'people') Town.peopleSheet(); else Town.open(o); };
$('#btn-help2').onclick = () => UI.help(true);
$('#btn-gear').onclick = () => UI.openInv();
$('#btn-sound2').onclick = () => { Sfx.on = !Sfx.on; $('#btn-sound2').textContent = $('#btn-sound').textContent = Sfx.on ? '🔊' : '🔇'; };
newRun();
View.buildFloor();
UI.syncAll();
UI.title();
window.__game = { clock: C, genFloorForTest: () => { genFloor(); View.buildFloor(); }, get META() { return META; }, Town, Game, enterDungeon, returnToTown, newHero, RECIPES, G, UI, View, act, playerMove, useStone, useItem, reduceColor, inCombat, descend,  computeFOV, addStone, pickGear, equip, unequip, makeGear, rollGear, calcStats, refreshStats, STONE, DROPS, hearthGlow, glowParts, requestState, acceptVisitor, rollVisitors, volunteers, takeTorch, openHidden, processReturn, regen: () => { genFloor(); View.buildFloor(); }, makeUnrand, stoneCd, gearName, loadMeta, resetMetaForTest: resetMeta, Settle };
