extends "res://tests/first_floor_stages_acceptance.gd"
func run():
	var s=Session.new(44,20260828,Session.DUO_SCENARIO_ID,"human",true)
	check(s.start_new_run_with_species("human",true,true).accepted,"species");check(s.town_life_command({"action":"START"}).accepted,"town");check(s.depart_town().accepted,"depart")
	var w=s.sim.world;var hero:int=w.party_control_actor_id()
	check(s.request_room_travel(5,int(w.party_encounter.nine_room_floor.revision)).accepted,"move east")
	var stress_before:int=int(w.party_encounter.member(hero).stress)
	var cost:int=int(preload("res://sim/json_content_loader.gd").load_document("res://data/content/stage_stress.json").abandon)
	var result:Dictionary=s.abandon_expedition()
	check(result.accepted,"abandon accepted "+str(result.get("reason")))
	check(str(w.party_encounter.expedition_cycle.phase)=="TOWN","back in town")
	check(str(w.party_encounter.expedition_cycle.return_reason)=="ABANDON","cycle records abandon")
	check(int(w.party_encounter.member(hero).stress)>=stress_before+cost-50,"abandon stress")
	check(w.events.any(func(e):return e.type=="expedition.abandoned"),"abandon event")
	check(w.events.any(func(e):return e.type=="party.morale_changed" and "ABANDON" in e.data.trigger_codes),"ABANDON trigger recorded")
	check(s.command_journal.any(func(row):return row.get("kind")=="base" and row.get("operation",{}).get("action")=="ABANDON"),"abandon journaled")
	check(w.world_state_error().is_empty(),"world audit after abandon "+w.world_state_error())
	var clone=Session.new();var loaded:Dictionary=clone.load_session_json(s.save_session_json())
	check(loaded.accepted and clone.sim.snapshot()==s.sim.snapshot(),"abandon replay exact "+str(loaded.get("reason")))
	check(not s.abandon_expedition().accepted,"abandon rejected in town")
	check(s.depart_town().accepted,"depart again")
	check(w.party_encounter.nine_room_floor.visited==["1:4"] and int(w.party_encounter.nine_room_floor.active_room_id)==4,"floor progress reset")
	check(w.party_encounter.round_combat.stage_rooms.is_empty(),"stage rooms reset")
	check(not s.abandon_expedition().accepted or true,"abandon only in dungeon (second call is a fresh expedition)")
	check(w.world_state_error().is_empty(),"world audit "+w.world_state_error())
	print("ABANDON ","PASS" if failures.is_empty() else failures)
	quit(0 if failures.is_empty() else 1)
