extends SceneTree
const Session=preload("res://playtest/party_playtest_session.gd")
const Fixture=preload("res://tests/round_combat_fixture.gd")
const Action=preload("res://sim/party_action_command.gd")
const Items=preload("res://sim/world_item_operations.gd")
const Growth=preload("res://sim/party_growth_rules.gd")
var failures:Array[String]=[]
func _init():run.call_deferred()
func check(ok:bool,label:String):
	if not ok:failures.append(label);printerr("FAIL ",label)
func run():
	var s=Fixture.create();var w=s.sim.world;var p=w.party_encounter
	var companion:int=p.active_party_member_ids[1];var enemy:int=p.enemy_ids[0]
	s._round_edit_actor_id=companion
	var edited:Dictionary=s.stage_round_action(Action.melee(companion,enemy))
	check(edited.get("accepted",false),"replace AI suggestion with attack")
	check(p.round_combat.plans[str(companion)].path.is_empty(),"attack clears suggested movement")
	check(p.round_combat.plans[str(companion)].action.type=="MELEE","attack remains attack")
	var grant:Dictionary=Items.commit_grant(w,p.protagonist_id,"POTION_MYSTERY_MANA",1,w.entities[p.protagonist_id].position,"PARTY_BAG_TEST")
	check(grant.get("accepted",false),"grant party potion")
	var item_id:String=str(grant.get("instance_id",""))
	p.member(companion).energy=0
	var use:Dictionary=s.use_party_item(item_id,companion)
	check(use.get("accepted",false),"stage companion potion "+str(use.get("reason")))
	check(w.inventory_of(p.protagonist_id).item(item_id)!=null,"planning does not consume item")
	var result:Dictionary=preload("res://sim/round_item_rules.gd").commit(s.sim,companion,p.round_combat.plans[str(companion)].item_operation)
	check(result.get("accepted",false),"companion consumes pooled potion "+str(result.get("reason")))
	check(p.member(companion).energy>0,"MP restored on companion")
	check(preload("res://sim/party_bag_rules.gd").owner(w,item_id)==-1,"exactly one shared item consumed")
	# Safe non-combat recruitment fixture exercises the real facade + save path.
	s=Session.new(44,20260828,Session.REGRESSION_SCENARIO_ID);w=s.sim.world;p=w.party_encounter
	companion=p.party_member_ids[1]
	if companion not in p.active_party_member_ids:p.active_party_member_ids.append(companion)
	p.member(companion).presence="GROUPED"
	p.member(companion).growth_xp=Session.GrowthBuildRegistryScript.xp_floor_for_level(3)
	check(s.mastery_status(companion).level==3 and s.mastery_status(companion).points==2,"NPC level 3 has two points")
	var spent:Dictionary=s.spend_mastery_point("MELEE",companion)
	check(spent.get("accepted",false),"NPC mastery commit "+str(spent.get("reason")))
	check(s.mastery_status().ranks.MELEE==0,"NPC investment does not affect hero")
	check(s.sim.melee._weapon_proficiency_rank(companion,"MELEE")==1,"NPC attacks use mastery")
	check(s.member_progression(companion).level==3,"NPC level is visible in character detail")
	var saved:Dictionary=s.sim.snapshot()
	var restored=Session.SimulatorScript.from_snapshot(saved)
	check(restored!=null,"NPC growth snapshot decodes")
	if restored!=null:check(Growth.for_actor(restored.world,companion).mastery_ranks.MELEE==1,"NPC mastery saved")
	var wire:Dictionary=JSON.parse_string(JSON.stringify(p.member(companion).to_dict()))
	check(preload("res://sim/party_member_state.gd").wire_error(wire).is_empty(),"NPC growth JSON validates")
	check(preload("res://sim/party_member_state.gd").from_dict(wire).mastery_ranks.MELEE==1,"NPC growth JSON roundtrip")
	p.ration_milli=100000
	grant=Items.commit_grant(w,p.protagonist_id,"ESSENCE_PREDATOR_NERVE",1,w.entities[p.protagonist_id].position,"PARTY_MEAT_TEST")
	item_id=str(grant.get("instance_id",""))
	use=s.use_party_item(item_id,companion)
	check(use.get("accepted",false),"feed special part to companion "+str(use.get("reason")))
	check("PREDATOR_NERVE" in s.sim.world.party_encounter.member(companion).bound_ability_ids,"only recipient gains mutation")
	check("PREDATOR_NERVE" not in s.sim.world.party_encounter.member(p.protagonist_id).bound_ability_ids,"hero mutation unchanged")
	var snapshot_after:Dictionary=s.sim.snapshot()
	restored=Session.SimulatorScript.from_snapshot(snapshot_after)
	check(restored!=null,"pooled meat + NPC growth snapshot validates")
	grant=Items.commit_grant(s.sim.world,companion,"POTION_MYSTERY_MANA",1,s.sim.world.entities[companion].position,"SHARED_ROW_TEST")
	item_id=str(grant.get("instance_id",""))
	check(s.protagonist_inventory().backpack_rows.any(func(row):return row.instance_id==item_id),"hero sees companion-held items in common bag")
	check(s.protagonist_inventory(companion).backpack_rows.map(func(row):return row.instance_id)==s.protagonist_inventory().backpack_rows.map(func(row):return row.instance_id),"all members see same bag")
	var bag_before:Dictionary=s.sim.snapshot()
	check(not s.use_party_item(item_id,p.enemy_ids[0]).get("accepted",false),"enemy cannot receive party consumable")
	check(s.sim.snapshot()==bag_before,"invalid recipient does not consume or transfer")
	grant=Items.commit_grant(s.sim.world,p.protagonist_id,"ARMOR_PADDED",1,s.sim.world.entities[p.protagonist_id].position,"SHARED_EQUIP_TEST")
	var equipped:Dictionary=s.party_item_operation("EQUIP",str(grant.get("instance_id","")),"ARMOR",companion)
	check(equipped.get("accepted",false),"equip pooled item on selected companion "+str(equipped.get("reason")))
	check(s.sim.world.equipped_item(companion,"ARMOR")!=null,"companion equipment is separate from bag")
	var bag_rules=preload("res://sim/party_bag_rules.gd")
	check(s.protagonist_inventory().capacity==preload("res://sim/inventory_state.gd").BACKPACK_CAPACITY,"one shared capacity, not one bag per portrait")
	check(s.protagonist_inventory().used_backpack_slots==bag_rules.used_slots(s.sim.world),"shared slot count includes every member")
	check(s._journal_wire_error(s.command_journal).is_empty(),"new operations journal validates")
	print("PARTY GROWTH BAG: ",failures);quit(0 if failures.is_empty() else 1)
