extends "res://tests/stage_counterplay_acceptance.gd"
func run():
	var s=Session.new(44,20260828,Session.DUO_SCENARIO_ID,"human",true)
	var w=s.sim.world;var hero:int=w.party_control_actor_id()
	check(s.start_new_run_with_species("human",true,true).accepted,"new run")
	check(s.town_life_command({"action":"START"}).accepted,"town")
	check(s.depart_town().accepted,"depart")
	w=s.sim.world;hero=w.party_control_actor_id()
	var npc:int=int(Population.locations(w)[0].entity_id)
	check(walk(s,Vector2i(14,11)),"walk east")
	check(s.request_room_exit(hero,"F1_R4_R5",w.party_encounter.nine_room_floor.revision).accepted,"enter event")
	check(walk(s,Stages.npc_position()+Vector2i.LEFT),"approach NPC")
	check(Visitors.interact(s,{"action":"AID","entity_id":str(npc)}).accepted,"aid")
	check(Visitors.interact(s,{"action":"ACCEPT","entity_id":str(npc)}).accepted,"recruit")
	check(walk(s,Vector2i(17,11)),"walk west")
	gather(s,npc,Vector2i(18,11),hero)
	check(s.request_room_exit(hero,"F1_R4_R5",w.party_encounter.nine_room_floor.revision).accepted,"return entry")
	check(walk(s,Vector2i(11,14)),"walk south")
	gather(s,npc,Vector2i(12,14),hero)
	check(s.request_room_exit(hero,"F1_R4_R7",w.party_encounter.nine_room_floor.revision).accepted,"combat")
	check(advance(s).accepted,"deploy")
	var before:Dictionary=s.sim.snapshot()
	root.size=Vector2i(360,800);root.content_scale_size=Vector2i(360,800)
	var ui=preload("res://playtest/party_encounter_sandbox.gd").new()
	ui.initialize_for_headless_test(s,true);root.add_child(ui);ui.set_process(false)
	for i in range(4):await process_frame
	var r:Dictionary=w.party_encounter.round_combat
	check(s.stage_round_action(Action.hold(hero)).accepted,"hero ends")
	var result:=advance(s)
	check(result.accepted and not result.round_result.completed,"first ally stops before second")
	check(Rules.current_actor(w)==npc,"recruited NPC receives own turn")
	ui._request_refresh()
	for i in range(4):await process_frame
	check(ui.selected_member_id==npc and ui.grid.selected_actor_id==npc,"UI automatically selects current companion")
	check(ui.stage_context_bar.get_node_or_null("StagePortrait%d"%npc)!=null,"footer belongs to current companion")
	check(not s.stage_round_action(Action.hold(hero)).accepted,"past hero cannot act on NPC turn")
	check(s.stage_round_action(Action.hold(npc)).accepted,"NPC can wait")
	result=advance(s)
	check(result.accepted and result.round_result.completed,"second ally completes cycle")
	check(w.world_state_error().is_empty(),"recruited cycle audit "+w.world_state_error())
	# Replaying every individual mutation must reproduce the same cursor and ledger.
	var clone=Session.new();var loaded:Dictionary=clone.load_session_json(s.save_session_json())
	check(loaded.accepted,"party turn journal replay "+str(loaded.get("reason")))
	if loaded.accepted:check(clone.sim.snapshot()==s.sim.snapshot(),"party turn replay exact")
	var shadow=preload("res://sim/simulator.gd").from_snapshot(before)
	if shadow!=null:mixed_checks(shadow,hero)
	else:check(false,"party fixture restores")
	ui.queue_free();await process_frame
	print("SRPG_PARTY_TURNS ","PASS" if failures.is_empty() else failures)
	quit(0 if failures.is_empty() else 1)

func gather(s,npc:int,to:Vector2i,hero:int):
	check(s.select_field_actor(npc).accepted,"select companion for doorway gathering")
	check(walk(s,to),"gather companion at doorway")
	check(s.select_field_actor(hero).accepted,"restore protagonist control")
