import test from 'node:test';import assert from 'node:assert/strict';
import { arena, enemy, advance } from './helpers.mjs';
import { createGear, equip, recalculate, enhance } from '../../js/sim/gear.js';
import { strike, attackShape, resolveTelegraphs } from '../../js/sim/combat.js';
import { shapeContains } from '../../js/sim/space.js';
import { WEAPONS } from '../../js/data/weapons.js';
import { addCompanion, setCommand } from '../../js/sim/party.js';
import { raidThink } from '../../js/sim/dungeon/raid.js';
import { cast } from '../../js/sim/roles.js';
import { B } from '../../js/data/balance.js';
test('대검은 앞 반원만 베고 창은 긴 한 줄을 찌른다',()=>{const w=arena(),h=w.units[0];h.facing=0;const s=attackShape(h,WEAPONS.greatsword);assert.ok(shapeContains(s,{x:6.5,y:5.5,radius:0.2}));assert.equal(shapeContains(s,{x:4.5,y:5.5,radius:0.2}),false);const p=attackShape(h,WEAPONS.pike);assert.ok(shapeContains(p,{x:7.5,y:5.5,radius:0.2}));assert.equal(shapeContains(p,{x:6.5,y:6.5,radius:0.2}),false);});
test('양손 무기를 입으면 방패가 가방으로 돌아간다',()=>{const w=arena(),h=w.units[0],shield=createGear(w,'shield'),g=createGear(w,'greatsword');h.inventory.push(shield,g);equip(w,h,shield.id);equip(w,h,g.id);assert.equal(h.gear.shield,undefined);assert.ok(h.inventory.includes(shield));assert.equal(h.weapon,'greatsword');});
test('강화와 속성은 실제 피해와 원소 반응에 적용된다',()=>{const w=arena(),h=w.units[0],e=enemy(w,'boar',7,7);h.gear.weapon.brand='fire';const before=h.damage;enhance(w,h,h.gear.weapon);assert.equal(h.damage,before+1);strike(w,h,e);assert.ok(e.statuses.burn);});
test('동료도 멈춘 동안 움직이거나 치유하지 않는다',()=>{const w=arena(),u=addCompanion(w,{name:'ally',id:'a',role:'healer',stance:'support'});w.flowing=false;const hp=w.units[0].hp=50,position={x:u.x,y:u.y};advance(w,3);assert.equal(w.units[0].hp,hp);assert.equal(u.x,position.x);assert.equal(u.y,position.y);});
test('수호자의 도발은 적의 위협 대상을 바꾼다',()=>{const w=arena(),h=w.units[0],e=enemy(w);h.role='guardian';assert.ok(cast(w,h,'taunt'));assert.equal(e.target,h.id);assert.equal(e.threat[h.id],100);});
test('레이드의 흩어짐은 겹친 범위에서 두 배 피해를 준다',()=>{const w=arena({}),boss=enemy(w,'keeper',10,10);const h=w.units[0];h.gear={};h.armor=0;const a=addCompanion(w,{name:'a',id:'a',role:'guardian'});a.x=h.x+0.6;a.y=h.y;a.armor=0;w.raidIndex=1;raidThink(w,boss,0.05);const before=h.hp;w.time=B.raidTell;resolveTelegraphs(w);assert.equal(before-h.hp,B.enemyDamage.keeper*4);});
test('레이드 모이기는 피해를 함께 나눈다',()=>{const w=arena(),boss=enemy(w,'keeper',10,10),h=w.units[0];h.armor=0;const a=addCompanion(w,{name:'a',id:'a',role:'guardian'});a.x=h.x+0.6;a.y=h.y;a.armor=0;w.raidIndex=2;raidThink(w,boss,0.05);const before=h.hp;w.time=B.raidTell;resolveTelegraphs(w);assert.equal(before-h.hp,B.enemyDamage.keeper);});
test('주간 씨앗이 레이드 기믹 순서를 바꾼다',()=>{const orders=[];for(const seed of [1,2]){const w=arena(seed,{weekly:true}),boss=enemy(w,'keeper',10,10);raidThink(w,boss,0.05);orders.push(w.events.find(e=>e.type==='mechanic').kind);}assert.notEqual(orders[0],orders[1]);});
